FirstProject/FirstProject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('processconfig.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FirstProject/processconfig/urls.py
from django.urls import path

from . import views

app_name = "processconfig"
urlpatterns = [
    path('', views.FileConfigurationView.as_view(), name='index'),
    path('<int:pk>/', views.FileConfigurationForProjectView.as_view(), name='project'),
    path('<int:pk>/update/', views.FileConfigurationUpdateView.as_view(), name='update_flow'),
    path('<int:pk>/create/', views.CreateFlowView.as_view(), name='create_flow'),
    path('sas_program/delete/<int:pk>/', views.FileDeleteView.as_view(), name='sas_program_delete'),
    path('sas_program/change_order/', views.ChangeSASProgramOrderView.as_view(), name="change_order"),
    path('generate/<int:pk>/', views.GenerateFile.as_view(), name="generate_file"),
]

FirstProject/processconfig/models.py
from django.db import models


class SASPrograms(models.Model):
    sas_program = models.FileField(upload_to="files")
    order_number = models.IntegerField(default=0)
    sas_program_name = models.CharField(max_length=100, default="")

    class Meta:
        verbose_name = "SASProgram"
        verbose_name_plural = "SASPrograms"

    def __str__(self):
        return f"{self.sas_program_name}"


class ProgramFlows(models.Model):
    flow_order_number = models.IntegerField(default=0)
    flow_name = models.CharField(default="", max_length=250)
    sas_programs = models.ManyToManyField(SASPrograms, blank=True)

    class Meta:
        verbose_name = "Flow number"
        verbose_name_plural = "Flows number"

    def __str__(self):
        return f"{self.flow_name} with {self.sas_programs.all().count()}"


class ProcessFlows(models.Model):
    project_name = models.CharField(max_length=100, default="")
    flows = models.ManyToManyField(ProgramFlows, blank=True)
    zip_file = models.FileField(blank=True, null=True)

    class Meta:
        verbose_name = "Process Flow"
        verbose_name_plural = "Process Flows"

    def __str__(self):
        return f"{self.project_name}"

FirstProject/processconfig/forms.py
from django import forms
from . import models


class FileUploadForm(forms.Form):
    flow_name = forms.CharField(max_length=250)
    sas_program = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))


class FileUploadWithProjectNameForm(FileUploadForm):
    project_name = forms.CharField(max_length=250)

FirstProject/processconfig/views.py
from django.http import HttpResponse, FileResponse, JsonResponse
from django.views import View, generic
from django.shortcuts import render, redirect, reverse
from django.template import loader
from django.db.models import Max
from . import forms
from . import models
import json
from .utils import get_table


class FileConfigurationView(View):
    def get(self, request, *args, **kwargs):
        template = loader.get_template("sas_config_main.html")
        context = {}
        return HttpResponse(template.render(context, request))

    def post(self, request, *args, **kwargs):
        form = forms.FileUploadWithProjectNameForm(request.POST, request.FILES)
        if form.is_valid():
            project_name = models.ProcessFlows.objects.create(
                project_name=request.POST["project_name"]
            )
            flow = models.ProgramFlows.objects.create(
                flow_name=request.POST["flow_name"]
            )
            project_name.flows.add(flow)
            for i, file in enumerate(request.FILES.getlist("sas_program")):
                new_file = models.SASPrograms.objects.create(
                    sas_program=file,
                    order_number=i,
                    sas_program_name=file
                )
                flow.sas_programs.add(new_file)
            return redirect(reverse('processconfig:project', kwargs={"pk":project_name.id}))
        return redirect(reverse('processconfig:index'))


class FileConfigurationForProjectView(View):
    def get(self, request, *args, **kwargs):
        template = loader.get_template("sas_config_project.html")
        project = models.ProcessFlows.objects.get(id=kwargs.get("pk"))
        flows = project.flows.all()
        context = {
            "flows": flows,
            "project": project,
            "pk": kwargs.get("pk"),
        }
        return HttpResponse(template.render(context, request))


class FileConfigurationUpdateView(View):
    def post(self, request, *args, **kwargs):
        flow = models.ProgramFlows.objects.get(pk=kwargs.get("pk"))
        form = forms.FileUploadForm(request.POST, request.FILES)

        if form.is_valid():
            flow.flow_name = request.POST.get("flow_name")
            flow.save()
            start = flow.sas_programs.all().aggregate(max_flow=Max('order_number'))["max_flow"] + 1
            for i, file in enumerate(request.FILES.getlist("sas_program"), start=start):
                new_file = models.SASPrograms.objects.create(
                    sas_program=file,
                    order_number=i,
                    sas_program_name=file
                )
                flow.sas_programs.add(new_file)
        return redirect(reverse('processconfig:project', kwargs={"pk": flow.processflows_set.all().first().id}))


class CreateFlowView(View):
    def post(self, request, *args, **kwargs):
        project = models.ProcessFlows.objects.get(id=kwargs.get("pk"))
        form = forms.FileUploadForm(request.POST, request.FILES)
        if form.is_valid():
            flow = models.ProgramFlows.objects.create(flow_name=request.POST.get("flow_name"))
            project.flows.add(flow)
            for i, file in enumerate(request.FILES.getlist("sas_program")):
                new_file = models.SASPrograms.objects.create(
                    sas_program=file,
                    order_number=i,
                    sas_program_name=file
                )
                flow.sas_programs.add(new_file)
        return redirect(reverse('processconfig:project', kwargs={"pk": kwargs.get("pk")}))


class FileDeleteView(generic.DeleteView):
    model = models.SASPrograms
    queryset = model.objects.all()

    def delete(self, request, *args, **kwargs):
        file = self.get_object()
        program_flow = models.ProgramFlows.objects.get(sas_programs=file)
        file.delete()
        if program_flow.sas_programs.all().count() == 0:
            project = models.ProcessFlows.objects.get(flows=program_flow)
            program_flow.delete()
            return JsonResponse({"response": "refresh"})
        return JsonResponse({"response": "deleted"})


class ChangeSASProgramOrderView(View):

    def post(self, request, *args, **kwargs):
        for element in json.load(request):
            sas_program = models.SASPrograms.objects.get(id=element.get("id"))
            sas_program.order_number = element.get("order_number")
            sas_program.save()
        return HttpResponse("changed")


class GenerateFile(View):
    def get(self, request, *args, **kwargs):
        file = get_table(kwargs.get("pk"))
        return FileResponse(file, as_attachment=True)

FirstProject/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SAS Config Generator</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"
        integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU"
        crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js"
        integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj"
        crossorigin="anonymous"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>

    <!-- jQuery UI CSS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>

</head>
<body>
<h1 class="text-center" style="padding-top:20px;">SAS EGP Packager</h1>
<div class="container" style="padding-top:60px">
    <div class="col-12">
        {% block content %}

        {% endblock content %}
    </div>
</div>
<script src="{% static 'js/script.js' %}"></script>


</body>
</html>

FirstProject/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SAS Config Generator</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

</head>
<body>
<div class="container" style="padding-top:60px">
    <div class="col-9">
        <form action="{% url 'processconfig:index' %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
            <div class="input-group mb-3">
                <span class="input-group-text" id="basic-addon1">Project Name</span>
                <input type="text" class="form-control" name="project_name" id="project_name">
            </div>
            <div class="mb-3">
                <label for="sas_program" class="form-label">Multiple files input example</label>
                <input class="form-control" type="file" name="sas_program" id="sas_program" multiple>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"
        integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js"
        integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj"
        crossorigin="anonymous"></script>

</body>
</html>

FirstProject/templates/sas_config_main.html
{% extends 'base.html' %}
{% block content %}
<form action="{% url 'processconfig:index' %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
        <div class="input-group mb-3">
            <span class="input-group-text">Project Name</span>
            <input type="text" class="form-control" name="project_name" id="project_name">
        </div>
        <div class="input-group mb-3">
            <span class="input-group-text">Flow name</span>
            <input type="text" class="form-control" name="flow_name">
        </div>
        <div class="mb-3">
            <label for="sas_program" class="form-label">Multiple files input example</label>
            <input class="form-control" type="file" name="sas_program" id="sas_program" multiple>
        </div>
        <button type="submit" class="btn btn-primary">Add files</button>
</form>
{% endblock content %}

FirstProject/templates/sas_config_project.html
{% extends 'base.html' %}
{% block content %}

    <form action="#" enctype="multipart/form-data">{% csrf_token %}
        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon1">Project Name</span>
            <input type="text" class="form-control" value="{{ project.project_name }}">
        </div>
    </form>
    {% for i in flows %}
        <div class="card">
            <div class="card-body">
            <form action="{% url 'processconfig:update_flow' i.id %}" enctype="multipart/form-data" method="POST">{% csrf_token %}
                <div class="input-group mb-3">
                    <span class="input-group-text">Flow name</span>
                    <input type="text" class="form-control" name="flow_name" value="{{ i.flow_name }}">
                </div>
                <div class="mb-3">
                    <label for="sas_program" class="form-label">Click here to choose files.</label>
                    <input class="form-control" type="file" name="sas_program" multiple>
                </div>
                <button type="submit" class="btn btn-primary">Add files</button>
            </form>
            {% if i.sas_programs.all|length > 0 %}
                <table class="table table-hover" id="flow_table{{ i.id }}">
                  <thead>
                    <tr>
                      <th scope="col">Order #</th>
                      <th scope="col">File Name</th>
                      <th scope="col">.</th>
                    </tr>
                  </thead>
                    <tbody>
                    {% for file in i.sas_programs.all|dictsort:"order_number" %}
                        <tr>
                          <th scope="row" class="priority" id="{{ file.id }}">{{ file.order_number }}</th>
                          <td>{{ file.sas_program_name }}</td>
                          <td><a class="btn btn-delete btn-danger" id="{{ file.id }}">Delete</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% endif %}

        </div>
    {% endfor %}

    </div>
    <div class="card">
        <div class="card-body">
            <div class="collapse" id="collapseExample">

                <form action="{% url 'processconfig:create_flow' pk %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
                    <div class="input-group mb-3">
                        <span class="input-group-text">Flow name</span>
                        <input type="text" class="form-control" name="flow_name">
                    </div>
                    <div class="mb-3">
                        <label for="sas_program" class="form-label">Click here to choose files.</label>
                        <input class="form-control" type="file" name="sas_program" multiple>
                    </div>
                    <button type="submit" class="btn btn-primary">Add files</button>

                </form>
            </div>
        </div>
        <div class="card-body">
            <button class="btn btn-primary" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                Add new flow
            </button>
            <a href="{% url 'processconfig:generate_file' pk %}" class="btn btn-primary">Generate configuration</a>
        </div>
    </div>
{% endblock content %}